name: Lint and test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-interaction --no-progress --optimize-autoloader"
      - name: Check for coding style
        run: vendor/bin/php-cs-fixer fix --dry-run
      - name: PHPUnit
        run: vendor/bin/phpunit -c build/phpunit.xml
      - name: Installing npm dependencies (for testing only)
        run: npm ci
      - name: Run PHP built-in webserver (in background) and newman tests
        run: | 
          php -S localhost:8000 example/server.php & 
          npx newman run -e tests/postman/tus.postman_environment.json tests/postman/tus.postman_collection.json --bail